// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// SignUpPost implements POST /sign-up operation.
//
// Register new user.
//
// POST /sign-up
func (UnimplementedHandler) SignUpPost(ctx context.Context, req *SignUpPostReq) (r *SignUpPostOK, _ error) {
	return r, ht.ErrNotImplemented
}
