// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1AuthRefreshPost implements POST /api/v1/auth/refresh operation.
//
// Refresh token pair.
//
// POST /api/v1/auth/refresh
func (UnimplementedHandler) APIV1AuthRefreshPost(ctx context.Context, params APIV1AuthRefreshPostParams) (r *APIV1AuthRefreshPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1AuthSignInPost implements POST /api/v1/auth/sign-in operation.
//
// Login.
//
// POST /api/v1/auth/sign-in
func (UnimplementedHandler) APIV1AuthSignInPost(ctx context.Context, req *APIV1AuthSignInPostReq) (r *APIV1AuthSignInPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1AuthSignUpPost implements POST /api/v1/auth/sign-up operation.
//
// Register new user.
//
// POST /api/v1/auth/sign-up
func (UnimplementedHandler) APIV1AuthSignUpPost(ctx context.Context, req *APIV1AuthSignUpPostReq) (r *APIV1AuthSignUpPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyDownloadIDGet implements GET /api/v1/cloud/storage/my/download/{id} operation.
//
// Download file by ID.
//
// GET /api/v1/cloud/storage/my/download/{id}
func (UnimplementedHandler) APIV1CloudStorageMyDownloadIDGet(ctx context.Context, params APIV1CloudStorageMyDownloadIDGetParams) (r APIV1CloudStorageMyDownloadIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyFileInfoGet implements GET /api/v1/cloud/storage/my/{file}/info operation.
//
// Get file metadata by ID or path.
//
// GET /api/v1/cloud/storage/my/{file}/info
func (UnimplementedHandler) APIV1CloudStorageMyFileInfoGet(ctx context.Context, params APIV1CloudStorageMyFileInfoGetParams) (r *APIV1CloudStorageMyFileInfoGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyGet implements GET /api/v1/cloud/storage/my operation.
//
// List user's files (paginated).
//
// GET /api/v1/cloud/storage/my
func (UnimplementedHandler) APIV1CloudStorageMyGet(ctx context.Context, params APIV1CloudStorageMyGetParams) (r *APIV1CloudStorageMyGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyUploadPost implements POST /api/v1/cloud/storage/my/upload operation.
//
// Create upload session.
//
// POST /api/v1/cloud/storage/my/upload
func (UnimplementedHandler) APIV1CloudStorageMyUploadPost(ctx context.Context, req *APIV1CloudStorageMyUploadPostReq) (r APIV1CloudStorageMyUploadPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyUploadUploadIDCompletePost implements POST /api/v1/cloud/storage/my/upload/{upload_id}/complete operation.
//
// Finalize upload.
//
// POST /api/v1/cloud/storage/my/upload/{upload_id}/complete
func (UnimplementedHandler) APIV1CloudStorageMyUploadUploadIDCompletePost(ctx context.Context, params APIV1CloudStorageMyUploadUploadIDCompletePostParams) (r APIV1CloudStorageMyUploadUploadIDCompletePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyUploadUploadIDGet implements GET /api/v1/cloud/storage/my/upload/{upload_id} operation.
//
// Get upload session status.
//
// GET /api/v1/cloud/storage/my/upload/{upload_id}
func (UnimplementedHandler) APIV1CloudStorageMyUploadUploadIDGet(ctx context.Context, params APIV1CloudStorageMyUploadUploadIDGetParams) (r APIV1CloudStorageMyUploadUploadIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1CloudStorageMyUploadUploadIDPut implements PUT /api/v1/cloud/storage/my/upload/{upload_id} operation.
//
// Upload a single chunk.
//
// PUT /api/v1/cloud/storage/my/upload/{upload_id}
func (UnimplementedHandler) APIV1CloudStorageMyUploadUploadIDPut(ctx context.Context, req APIV1CloudStorageMyUploadUploadIDPutReq, params APIV1CloudStorageMyUploadUploadIDPutParams) (r APIV1CloudStorageMyUploadUploadIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
