// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type APIV1AuthRefreshPostOK struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *APIV1AuthRefreshPostOK) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *APIV1AuthRefreshPostOK) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *APIV1AuthRefreshPostOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *APIV1AuthRefreshPostOK) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type APIV1AuthSignInPostOK struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *APIV1AuthSignInPostOK) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *APIV1AuthSignInPostOK) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *APIV1AuthSignInPostOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *APIV1AuthSignInPostOK) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type APIV1AuthSignInPostReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *APIV1AuthSignInPostReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *APIV1AuthSignInPostReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *APIV1AuthSignInPostReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *APIV1AuthSignInPostReq) SetPassword(val string) {
	s.Password = val
}

type APIV1AuthSignUpPostOK struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *APIV1AuthSignUpPostOK) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *APIV1AuthSignUpPostOK) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *APIV1AuthSignUpPostOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *APIV1AuthSignUpPostOK) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type APIV1AuthSignUpPostReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *APIV1AuthSignUpPostReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *APIV1AuthSignUpPostReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *APIV1AuthSignUpPostReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *APIV1AuthSignUpPostReq) SetPassword(val string) {
	s.Password = val
}

type APIV1CloudStorageMyDownloadIDGetForbidden struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetForbidden) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetForbidden) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyDownloadIDGetForbidden) aPIV1CloudStorageMyDownloadIDGetRes() {}

type APIV1CloudStorageMyDownloadIDGetNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyDownloadIDGetNotFound) aPIV1CloudStorageMyDownloadIDGetRes() {}

type APIV1CloudStorageMyDownloadIDGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIV1CloudStorageMyDownloadIDGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*APIV1CloudStorageMyDownloadIDGetOK) aPIV1CloudStorageMyDownloadIDGetRes() {}

type APIV1CloudStorageMyFileInfoGetOK struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Size      int    `json:"size"`
	MimeType  string `json:"mime_type"`
	FilePath  string `json:"file_path"`
	CreatedAt string `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetName() string {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetSize() int {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetMimeType() string {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetFilePath() string {
	return s.FilePath
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetName(val string) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetSize(val int) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetMimeType(val string) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetFilePath(val string) {
	s.FilePath = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetCreatedAt(val string) {
	s.CreatedAt = val
}

type APIV1CloudStorageMyGetOK struct {
	Files   []APIV1CloudStorageMyGetOKFilesItem `json:"files"`
	Total   int                                 `json:"total"`
	UsedGbs float64                             `json:"used_gbs"`
}

// GetFiles returns the value of Files.
func (s *APIV1CloudStorageMyGetOK) GetFiles() []APIV1CloudStorageMyGetOKFilesItem {
	return s.Files
}

// GetTotal returns the value of Total.
func (s *APIV1CloudStorageMyGetOK) GetTotal() int {
	return s.Total
}

// GetUsedGbs returns the value of UsedGbs.
func (s *APIV1CloudStorageMyGetOK) GetUsedGbs() float64 {
	return s.UsedGbs
}

// SetFiles sets the value of Files.
func (s *APIV1CloudStorageMyGetOK) SetFiles(val []APIV1CloudStorageMyGetOKFilesItem) {
	s.Files = val
}

// SetTotal sets the value of Total.
func (s *APIV1CloudStorageMyGetOK) SetTotal(val int) {
	s.Total = val
}

// SetUsedGbs sets the value of UsedGbs.
func (s *APIV1CloudStorageMyGetOK) SetUsedGbs(val float64) {
	s.UsedGbs = val
}

type APIV1CloudStorageMyGetOKFilesItem struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Size      int    `json:"size"`
	MimeType  string `json:"mime_type"`
	FilePath  string `json:"file_path"`
	CreatedAt string `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetName() string {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetSize() int {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetMimeType() string {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetFilePath() string {
	return s.FilePath
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetName(val string) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetSize(val int) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetMimeType(val string) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetFilePath(val string) {
	s.FilePath = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetCreatedAt(val string) {
	s.CreatedAt = val
}

type APIV1CloudStorageMyUploadPostBadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadPostBadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadPostBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadPostBadRequest) aPIV1CloudStorageMyUploadPostRes() {}

type APIV1CloudStorageMyUploadPostCreated struct {
	UploadID  string `json:"upload_id"`
	ChunkSize int    `json:"chunk_size"`
	ExpiresAt string `json:"expires_at"`
}

// GetUploadID returns the value of UploadID.
func (s *APIV1CloudStorageMyUploadPostCreated) GetUploadID() string {
	return s.UploadID
}

// GetChunkSize returns the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadPostCreated) GetChunkSize() int {
	return s.ChunkSize
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadPostCreated) GetExpiresAt() string {
	return s.ExpiresAt
}

// SetUploadID sets the value of UploadID.
func (s *APIV1CloudStorageMyUploadPostCreated) SetUploadID(val string) {
	s.UploadID = val
}

// SetChunkSize sets the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadPostCreated) SetChunkSize(val int) {
	s.ChunkSize = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadPostCreated) SetExpiresAt(val string) {
	s.ExpiresAt = val
}

func (*APIV1CloudStorageMyUploadPostCreated) aPIV1CloudStorageMyUploadPostRes() {}

type APIV1CloudStorageMyUploadPostInsufficientStorage struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadPostInsufficientStorage) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadPostInsufficientStorage) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadPostInsufficientStorage) aPIV1CloudStorageMyUploadPostRes() {}

type APIV1CloudStorageMyUploadPostReq struct {
	Name     string `json:"name"`
	Size     int    `json:"size"`
	MimeType string `json:"mime_type"`
	FilePath string `json:"file_path"`
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyUploadPostReq) GetName() string {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyUploadPostReq) GetSize() int {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyUploadPostReq) GetMimeType() string {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyUploadPostReq) GetFilePath() string {
	return s.FilePath
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyUploadPostReq) SetName(val string) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyUploadPostReq) SetSize(val int) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyUploadPostReq) SetMimeType(val string) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyUploadPostReq) SetFilePath(val string) {
	s.FilePath = val
}

type APIV1CloudStorageMyUploadUploadIDCompletePostConflict struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostConflict) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostConflict) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDCompletePostConflict) aPIV1CloudStorageMyUploadUploadIDCompletePostRes() {
}

type APIV1CloudStorageMyUploadUploadIDCompletePostNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDCompletePostNotFound) aPIV1CloudStorageMyUploadUploadIDCompletePostRes() {
}

type APIV1CloudStorageMyUploadUploadIDCompletePostOK struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Size      int    `json:"size"`
	MimeType  string `json:"mime_type"`
	FilePath  string `json:"file_path"`
	CreatedAt string `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) GetName() string {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) GetSize() int {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) GetMimeType() string {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) GetFilePath() string {
	return s.FilePath
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) SetName(val string) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) SetSize(val int) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) SetMimeType(val string) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) SetFilePath(val string) {
	s.FilePath = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostOK) SetCreatedAt(val string) {
	s.CreatedAt = val
}

func (*APIV1CloudStorageMyUploadUploadIDCompletePostOK) aPIV1CloudStorageMyUploadUploadIDCompletePostRes() {
}

type APIV1CloudStorageMyUploadUploadIDGetNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDGetNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDGetNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDGetNotFound) aPIV1CloudStorageMyUploadUploadIDGetRes() {}

type APIV1CloudStorageMyUploadUploadIDGetOK struct {
	UploadID       string   `json:"upload_id"`
	Name           string   `json:"name"`
	Size           int      `json:"size"`
	ReceivedBytes  int      `json:"received_bytes"`
	ReceivedRanges []string `json:"received_ranges"`
	ChunkSize      int      `json:"chunk_size"`
	ExpiresAt      string   `json:"expires_at"`
}

// GetUploadID returns the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetUploadID() string {
	return s.UploadID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetName() string {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetSize() int {
	return s.Size
}

// GetReceivedBytes returns the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetReceivedBytes() int {
	return s.ReceivedBytes
}

// GetReceivedRanges returns the value of ReceivedRanges.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetReceivedRanges() []string {
	return s.ReceivedRanges
}

// GetChunkSize returns the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetChunkSize() int {
	return s.ChunkSize
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetExpiresAt() string {
	return s.ExpiresAt
}

// SetUploadID sets the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetUploadID(val string) {
	s.UploadID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetName(val string) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetSize(val int) {
	s.Size = val
}

// SetReceivedBytes sets the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetReceivedBytes(val int) {
	s.ReceivedBytes = val
}

// SetReceivedRanges sets the value of ReceivedRanges.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetReceivedRanges(val []string) {
	s.ReceivedRanges = val
}

// SetChunkSize sets the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetChunkSize(val int) {
	s.ChunkSize = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetExpiresAt(val string) {
	s.ExpiresAt = val
}

func (*APIV1CloudStorageMyUploadUploadIDGetOK) aPIV1CloudStorageMyUploadUploadIDGetRes() {}

type APIV1CloudStorageMyUploadUploadIDPutConflict struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutConflict) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutConflict) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutConflict) aPIV1CloudStorageMyUploadUploadIDPutRes() {}

type APIV1CloudStorageMyUploadUploadIDPutNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutNotFound) aPIV1CloudStorageMyUploadUploadIDPutRes() {}

type APIV1CloudStorageMyUploadUploadIDPutOK struct {
	UploadID      string `json:"upload_id"`
	ReceivedBytes int    `json:"received_bytes"`
	TotalBytes    int    `json:"total_bytes"`
}

// GetUploadID returns the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) GetUploadID() string {
	return s.UploadID
}

// GetReceivedBytes returns the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) GetReceivedBytes() int {
	return s.ReceivedBytes
}

// GetTotalBytes returns the value of TotalBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) GetTotalBytes() int {
	return s.TotalBytes
}

// SetUploadID sets the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) SetUploadID(val string) {
	s.UploadID = val
}

// SetReceivedBytes sets the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) SetReceivedBytes(val int) {
	s.ReceivedBytes = val
}

// SetTotalBytes sets the value of TotalBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) SetTotalBytes(val int) {
	s.TotalBytes = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutOK) aPIV1CloudStorageMyUploadUploadIDPutRes() {}

type APIV1CloudStorageMyUploadUploadIDPutReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIV1CloudStorageMyUploadUploadIDPutReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge) aPIV1CloudStorageMyUploadUploadIDPutRes() {
}

type APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable) aPIV1CloudStorageMyUploadUploadIDPutRes() {
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}
