// Code generated by ogen, DO NOT EDIT.
package api

type APIV1CloudStorageMyDownloadIDGetRes interface {
	aPIV1CloudStorageMyDownloadIDGetRes()
}

type APIV1CloudStorageMyUploadPostRes interface {
	aPIV1CloudStorageMyUploadPostRes()
}

type APIV1CloudStorageMyUploadUploadIDCompletePostRes interface {
	aPIV1CloudStorageMyUploadUploadIDCompletePostRes()
}

type APIV1CloudStorageMyUploadUploadIDGetRes interface {
	aPIV1CloudStorageMyUploadUploadIDGetRes()
}

type APIV1CloudStorageMyUploadUploadIDPutRes interface {
	aPIV1CloudStorageMyUploadUploadIDPutRes()
}
