// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1AuthRefreshPost implements POST /api/v1/auth/refresh operation.
	//
	// Refresh token pair.
	//
	// POST /api/v1/auth/refresh
	APIV1AuthRefreshPost(ctx context.Context, params APIV1AuthRefreshPostParams) (*APIV1AuthRefreshPostOK, error)
	// APIV1AuthSignInPost implements POST /api/v1/auth/sign-in operation.
	//
	// Login.
	//
	// POST /api/v1/auth/sign-in
	APIV1AuthSignInPost(ctx context.Context, req *APIV1AuthSignInPostReq) (*APIV1AuthSignInPostOK, error)
	// APIV1AuthSignUpPost implements POST /api/v1/auth/sign-up operation.
	//
	// Register new user.
	//
	// POST /api/v1/auth/sign-up
	APIV1AuthSignUpPost(ctx context.Context, req *APIV1AuthSignUpPostReq) (*APIV1AuthSignUpPostOK, error)
	// APIV1CloudStorageMyDownloadIDGet implements GET /api/v1/cloud/storage/my/download/{id} operation.
	//
	// Download file by ID.
	//
	// GET /api/v1/cloud/storage/my/download/{id}
	APIV1CloudStorageMyDownloadIDGet(ctx context.Context, params APIV1CloudStorageMyDownloadIDGetParams) (APIV1CloudStorageMyDownloadIDGetRes, error)
	// APIV1CloudStorageMyFileInfoGet implements GET /api/v1/cloud/storage/my/{file}/info operation.
	//
	// Get file metadata by ID or path.
	//
	// GET /api/v1/cloud/storage/my/{file}/info
	APIV1CloudStorageMyFileInfoGet(ctx context.Context, params APIV1CloudStorageMyFileInfoGetParams) (*APIV1CloudStorageMyFileInfoGetOK, error)
	// APIV1CloudStorageMyGet implements GET /api/v1/cloud/storage/my operation.
	//
	// List user's files (paginated).
	//
	// GET /api/v1/cloud/storage/my
	APIV1CloudStorageMyGet(ctx context.Context, params APIV1CloudStorageMyGetParams) (*APIV1CloudStorageMyGetOK, error)
	// APIV1CloudStorageMyUploadPost implements POST /api/v1/cloud/storage/my/upload operation.
	//
	// Create upload session.
	//
	// POST /api/v1/cloud/storage/my/upload
	APIV1CloudStorageMyUploadPost(ctx context.Context, req *APIV1CloudStorageMyUploadPostReq) (APIV1CloudStorageMyUploadPostRes, error)
	// APIV1CloudStorageMyUploadUploadIDCompletePost implements POST /api/v1/cloud/storage/my/upload/{upload_id}/complete operation.
	//
	// Finalize upload.
	//
	// POST /api/v1/cloud/storage/my/upload/{upload_id}/complete
	APIV1CloudStorageMyUploadUploadIDCompletePost(ctx context.Context, params APIV1CloudStorageMyUploadUploadIDCompletePostParams) (APIV1CloudStorageMyUploadUploadIDCompletePostRes, error)
	// APIV1CloudStorageMyUploadUploadIDGet implements GET /api/v1/cloud/storage/my/upload/{upload_id} operation.
	//
	// Get upload session status.
	//
	// GET /api/v1/cloud/storage/my/upload/{upload_id}
	APIV1CloudStorageMyUploadUploadIDGet(ctx context.Context, params APIV1CloudStorageMyUploadUploadIDGetParams) (APIV1CloudStorageMyUploadUploadIDGetRes, error)
	// APIV1CloudStorageMyUploadUploadIDPut implements PUT /api/v1/cloud/storage/my/upload/{upload_id} operation.
	//
	// Upload a single chunk.
	//
	// PUT /api/v1/cloud/storage/my/upload/{upload_id}
	APIV1CloudStorageMyUploadUploadIDPut(ctx context.Context, req APIV1CloudStorageMyUploadUploadIDPutReq, params APIV1CloudStorageMyUploadUploadIDPutParams) (APIV1CloudStorageMyUploadUploadIDPutRes, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
