// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type APIV1AuthRefreshPostOK struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *APIV1AuthRefreshPostOK) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *APIV1AuthRefreshPostOK) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *APIV1AuthRefreshPostOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *APIV1AuthRefreshPostOK) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type APIV1AuthSignInPostOK struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *APIV1AuthSignInPostOK) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *APIV1AuthSignInPostOK) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *APIV1AuthSignInPostOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *APIV1AuthSignInPostOK) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type APIV1AuthSignInPostReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *APIV1AuthSignInPostReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *APIV1AuthSignInPostReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *APIV1AuthSignInPostReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *APIV1AuthSignInPostReq) SetPassword(val string) {
	s.Password = val
}

type APIV1AuthSignUpPostOK struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *APIV1AuthSignUpPostOK) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *APIV1AuthSignUpPostOK) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *APIV1AuthSignUpPostOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *APIV1AuthSignUpPostOK) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type APIV1AuthSignUpPostReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *APIV1AuthSignUpPostReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *APIV1AuthSignUpPostReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *APIV1AuthSignUpPostReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *APIV1AuthSignUpPostReq) SetPassword(val string) {
	s.Password = val
}

type APIV1CloudStorageMyDownloadIDGetForbidden struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetForbidden) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetForbidden) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyDownloadIDGetForbidden) aPIV1CloudStorageMyDownloadIDGetRes() {}

type APIV1CloudStorageMyDownloadIDGetNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyDownloadIDGetNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyDownloadIDGetNotFound) aPIV1CloudStorageMyDownloadIDGetRes() {}

type APIV1CloudStorageMyDownloadIDGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIV1CloudStorageMyDownloadIDGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*APIV1CloudStorageMyDownloadIDGetOK) aPIV1CloudStorageMyDownloadIDGetRes() {}

type APIV1CloudStorageMyFileInfoGetOK struct {
	ID        OptString `json:"id"`
	Name      OptString `json:"name"`
	Size      OptInt    `json:"size"`
	MimeType  OptString `json:"mime_type"`
	FilePath  OptString `json:"file_path"`
	CreatedAt OptString `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetName() OptString {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetSize() OptInt {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetMimeType() OptString {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetFilePath() OptString {
	return s.FilePath
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIV1CloudStorageMyFileInfoGetOK) GetCreatedAt() OptString {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetName(val OptString) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetSize(val OptInt) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetMimeType(val OptString) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetFilePath(val OptString) {
	s.FilePath = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIV1CloudStorageMyFileInfoGetOK) SetCreatedAt(val OptString) {
	s.CreatedAt = val
}

type APIV1CloudStorageMyGetOK struct {
	Files   []APIV1CloudStorageMyGetOKFilesItem `json:"files"`
	Total   OptInt                              `json:"total"`
	UsedGbs OptFloat64                          `json:"used_gbs"`
}

// GetFiles returns the value of Files.
func (s *APIV1CloudStorageMyGetOK) GetFiles() []APIV1CloudStorageMyGetOKFilesItem {
	return s.Files
}

// GetTotal returns the value of Total.
func (s *APIV1CloudStorageMyGetOK) GetTotal() OptInt {
	return s.Total
}

// GetUsedGbs returns the value of UsedGbs.
func (s *APIV1CloudStorageMyGetOK) GetUsedGbs() OptFloat64 {
	return s.UsedGbs
}

// SetFiles sets the value of Files.
func (s *APIV1CloudStorageMyGetOK) SetFiles(val []APIV1CloudStorageMyGetOKFilesItem) {
	s.Files = val
}

// SetTotal sets the value of Total.
func (s *APIV1CloudStorageMyGetOK) SetTotal(val OptInt) {
	s.Total = val
}

// SetUsedGbs sets the value of UsedGbs.
func (s *APIV1CloudStorageMyGetOK) SetUsedGbs(val OptFloat64) {
	s.UsedGbs = val
}

type APIV1CloudStorageMyGetOKFilesItem struct {
	ID        OptString `json:"id"`
	Name      OptString `json:"name"`
	Size      OptInt    `json:"size"`
	MimeType  OptString `json:"mime_type"`
	FilePath  OptString `json:"file_path"`
	CreatedAt OptString `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetName() OptString {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetSize() OptInt {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetMimeType() OptString {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetFilePath() OptString {
	return s.FilePath
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIV1CloudStorageMyGetOKFilesItem) GetCreatedAt() OptString {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetName(val OptString) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetSize(val OptInt) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetMimeType(val OptString) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetFilePath(val OptString) {
	s.FilePath = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIV1CloudStorageMyGetOKFilesItem) SetCreatedAt(val OptString) {
	s.CreatedAt = val
}

type APIV1CloudStorageMyUploadPostBadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadPostBadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadPostBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadPostBadRequest) aPIV1CloudStorageMyUploadPostRes() {}

type APIV1CloudStorageMyUploadPostCreated struct {
	UploadID  OptString `json:"upload_id"`
	ChunkSize OptInt    `json:"chunk_size"`
	ExpiresAt OptString `json:"expires_at"`
}

// GetUploadID returns the value of UploadID.
func (s *APIV1CloudStorageMyUploadPostCreated) GetUploadID() OptString {
	return s.UploadID
}

// GetChunkSize returns the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadPostCreated) GetChunkSize() OptInt {
	return s.ChunkSize
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadPostCreated) GetExpiresAt() OptString {
	return s.ExpiresAt
}

// SetUploadID sets the value of UploadID.
func (s *APIV1CloudStorageMyUploadPostCreated) SetUploadID(val OptString) {
	s.UploadID = val
}

// SetChunkSize sets the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadPostCreated) SetChunkSize(val OptInt) {
	s.ChunkSize = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadPostCreated) SetExpiresAt(val OptString) {
	s.ExpiresAt = val
}

func (*APIV1CloudStorageMyUploadPostCreated) aPIV1CloudStorageMyUploadPostRes() {}

type APIV1CloudStorageMyUploadPostInsufficientStorage struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadPostInsufficientStorage) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadPostInsufficientStorage) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadPostInsufficientStorage) aPIV1CloudStorageMyUploadPostRes() {}

type APIV1CloudStorageMyUploadPostReq struct {
	Name     string `json:"name"`
	Size     int    `json:"size"`
	MimeType string `json:"mime_type"`
	FilePath string `json:"file_path"`
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyUploadPostReq) GetName() string {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyUploadPostReq) GetSize() int {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyUploadPostReq) GetMimeType() string {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyUploadPostReq) GetFilePath() string {
	return s.FilePath
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyUploadPostReq) SetName(val string) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyUploadPostReq) SetSize(val int) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyUploadPostReq) SetMimeType(val string) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyUploadPostReq) SetFilePath(val string) {
	s.FilePath = val
}

type APIV1CloudStorageMyUploadUploadIDCompletePostConflict struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostConflict) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostConflict) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDCompletePostConflict) aPIV1CloudStorageMyUploadUploadIDCompletePostRes() {
}

type APIV1CloudStorageMyUploadUploadIDCompletePostCreated struct {
	ID        OptString `json:"id"`
	Name      OptString `json:"name"`
	Size      OptInt    `json:"size"`
	MimeType  OptString `json:"mime_type"`
	FilePath  OptString `json:"file_path"`
	CreatedAt OptString `json:"created_at"`
}

// GetID returns the value of ID.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) GetName() OptString {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) GetSize() OptInt {
	return s.Size
}

// GetMimeType returns the value of MimeType.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) GetMimeType() OptString {
	return s.MimeType
}

// GetFilePath returns the value of FilePath.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) GetFilePath() OptString {
	return s.FilePath
}

// GetCreatedAt returns the value of CreatedAt.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) GetCreatedAt() OptString {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) SetName(val OptString) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) SetSize(val OptInt) {
	s.Size = val
}

// SetMimeType sets the value of MimeType.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) SetMimeType(val OptString) {
	s.MimeType = val
}

// SetFilePath sets the value of FilePath.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) SetFilePath(val OptString) {
	s.FilePath = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostCreated) SetCreatedAt(val OptString) {
	s.CreatedAt = val
}

func (*APIV1CloudStorageMyUploadUploadIDCompletePostCreated) aPIV1CloudStorageMyUploadUploadIDCompletePostRes() {
}

type APIV1CloudStorageMyUploadUploadIDCompletePostNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDCompletePostNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDCompletePostNotFound) aPIV1CloudStorageMyUploadUploadIDCompletePostRes() {
}

type APIV1CloudStorageMyUploadUploadIDGetNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDGetNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDGetNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDGetNotFound) aPIV1CloudStorageMyUploadUploadIDGetRes() {}

type APIV1CloudStorageMyUploadUploadIDGetOK struct {
	UploadID       OptString `json:"upload_id"`
	Name           OptString `json:"name"`
	Size           OptInt    `json:"size"`
	ReceivedBytes  OptInt    `json:"received_bytes"`
	ReceivedRanges []string  `json:"received_ranges"`
	ChunkSize      OptInt    `json:"chunk_size"`
	ExpiresAt      OptString `json:"expires_at"`
}

// GetUploadID returns the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetUploadID() OptString {
	return s.UploadID
}

// GetName returns the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetName() OptString {
	return s.Name
}

// GetSize returns the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetSize() OptInt {
	return s.Size
}

// GetReceivedBytes returns the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetReceivedBytes() OptInt {
	return s.ReceivedBytes
}

// GetReceivedRanges returns the value of ReceivedRanges.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetReceivedRanges() []string {
	return s.ReceivedRanges
}

// GetChunkSize returns the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetChunkSize() OptInt {
	return s.ChunkSize
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) GetExpiresAt() OptString {
	return s.ExpiresAt
}

// SetUploadID sets the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetUploadID(val OptString) {
	s.UploadID = val
}

// SetName sets the value of Name.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetName(val OptString) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetSize(val OptInt) {
	s.Size = val
}

// SetReceivedBytes sets the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetReceivedBytes(val OptInt) {
	s.ReceivedBytes = val
}

// SetReceivedRanges sets the value of ReceivedRanges.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetReceivedRanges(val []string) {
	s.ReceivedRanges = val
}

// SetChunkSize sets the value of ChunkSize.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetChunkSize(val OptInt) {
	s.ChunkSize = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *APIV1CloudStorageMyUploadUploadIDGetOK) SetExpiresAt(val OptString) {
	s.ExpiresAt = val
}

func (*APIV1CloudStorageMyUploadUploadIDGetOK) aPIV1CloudStorageMyUploadUploadIDGetRes() {}

type APIV1CloudStorageMyUploadUploadIDPutConflict struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutConflict) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutConflict) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutConflict) aPIV1CloudStorageMyUploadUploadIDPutRes() {}

type APIV1CloudStorageMyUploadUploadIDPutNotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutNotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutNotFound) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutNotFound) aPIV1CloudStorageMyUploadUploadIDPutRes() {}

type APIV1CloudStorageMyUploadUploadIDPutOK struct {
	UploadID      OptString `json:"upload_id"`
	ReceivedBytes OptInt    `json:"received_bytes"`
	TotalBytes    OptInt    `json:"total_bytes"`
}

// GetUploadID returns the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) GetUploadID() OptString {
	return s.UploadID
}

// GetReceivedBytes returns the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) GetReceivedBytes() OptInt {
	return s.ReceivedBytes
}

// GetTotalBytes returns the value of TotalBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) GetTotalBytes() OptInt {
	return s.TotalBytes
}

// SetUploadID sets the value of UploadID.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) SetUploadID(val OptString) {
	s.UploadID = val
}

// SetReceivedBytes sets the value of ReceivedBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) SetReceivedBytes(val OptInt) {
	s.ReceivedBytes = val
}

// SetTotalBytes sets the value of TotalBytes.
func (s *APIV1CloudStorageMyUploadUploadIDPutOK) SetTotalBytes(val OptInt) {
	s.TotalBytes = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutOK) aPIV1CloudStorageMyUploadUploadIDPutRes() {}

type APIV1CloudStorageMyUploadUploadIDPutReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIV1CloudStorageMyUploadUploadIDPutReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutRequestEntityTooLarge) aPIV1CloudStorageMyUploadUploadIDPutRes() {
}

type APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable) SetMessage(val string) {
	s.Message = val
}

func (*APIV1CloudStorageMyUploadUploadIDPutRequestedRangeNotSatisfiable) aPIV1CloudStorageMyUploadUploadIDPutRes() {
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
