// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIV1AuthRefreshPostParams is parameters of POST /api/v1/auth/refresh operation.
type APIV1AuthRefreshPostParams struct {
	Token string
}

func unpackAPIV1AuthRefreshPostParams(packed middleware.Parameters) (params APIV1AuthRefreshPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "token",
			In:   "query",
		}
		params.Token = packed[key].(string)
	}
	return params
}

func decodeAPIV1AuthRefreshPostParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV1AuthRefreshPostParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: token.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "token",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Token = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "token",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1CloudStorageMyDownloadIDGetParams is parameters of GET /api/v1/cloud/storage/my/download/{id} operation.
type APIV1CloudStorageMyDownloadIDGetParams struct {
	ID string
}

func unpackAPIV1CloudStorageMyDownloadIDGetParams(packed middleware.Parameters) (params APIV1CloudStorageMyDownloadIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeAPIV1CloudStorageMyDownloadIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1CloudStorageMyDownloadIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1CloudStorageMyFileInfoGetParams is parameters of GET /api/v1/cloud/storage/my/{file}/info operation.
type APIV1CloudStorageMyFileInfoGetParams struct {
	File string
}

func unpackAPIV1CloudStorageMyFileInfoGetParams(packed middleware.Parameters) (params APIV1CloudStorageMyFileInfoGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "file",
			In:   "path",
		}
		params.File = packed[key].(string)
	}
	return params
}

func decodeAPIV1CloudStorageMyFileInfoGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1CloudStorageMyFileInfoGetParams, _ error) {
	// Decode path: file.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "file",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.File = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "file",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1CloudStorageMyGetParams is parameters of GET /api/v1/cloud/storage/my operation.
type APIV1CloudStorageMyGetParams struct {
	Limit OptInt `json:",omitempty,omitzero"`
	Page  OptInt `json:",omitempty,omitzero"`
}

func unpackAPIV1CloudStorageMyGetParams(packed middleware.Parameters) (params APIV1CloudStorageMyGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "page",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Page = v.(OptInt)
		}
	}
	return params
}

func decodeAPIV1CloudStorageMyGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV1CloudStorageMyGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: limit.
	{
		val := int(100)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: page.
	{
		val := int(1)
		params.Page.SetTo(val)
	}
	// Decode query: page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPageVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Page.SetTo(paramsDotPageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "page",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1CloudStorageMyUploadUploadIDCompletePostParams is parameters of POST /api/v1/cloud/storage/my/upload/{upload_id}/complete operation.
type APIV1CloudStorageMyUploadUploadIDCompletePostParams struct {
	UploadID string
}

func unpackAPIV1CloudStorageMyUploadUploadIDCompletePostParams(packed middleware.Parameters) (params APIV1CloudStorageMyUploadUploadIDCompletePostParams) {
	{
		key := middleware.ParameterKey{
			Name: "upload_id",
			In:   "path",
		}
		params.UploadID = packed[key].(string)
	}
	return params
}

func decodeAPIV1CloudStorageMyUploadUploadIDCompletePostParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1CloudStorageMyUploadUploadIDCompletePostParams, _ error) {
	// Decode path: upload_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "upload_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UploadID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "upload_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1CloudStorageMyUploadUploadIDGetParams is parameters of GET /api/v1/cloud/storage/my/upload/{upload_id} operation.
type APIV1CloudStorageMyUploadUploadIDGetParams struct {
	UploadID string
}

func unpackAPIV1CloudStorageMyUploadUploadIDGetParams(packed middleware.Parameters) (params APIV1CloudStorageMyUploadUploadIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "upload_id",
			In:   "path",
		}
		params.UploadID = packed[key].(string)
	}
	return params
}

func decodeAPIV1CloudStorageMyUploadUploadIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1CloudStorageMyUploadUploadIDGetParams, _ error) {
	// Decode path: upload_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "upload_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UploadID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "upload_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1CloudStorageMyUploadUploadIDPutParams is parameters of PUT /api/v1/cloud/storage/my/upload/{upload_id} operation.
type APIV1CloudStorageMyUploadUploadIDPutParams struct {
	UploadID     string
	ContentRange string
}

func unpackAPIV1CloudStorageMyUploadUploadIDPutParams(packed middleware.Parameters) (params APIV1CloudStorageMyUploadUploadIDPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "upload_id",
			In:   "path",
		}
		params.UploadID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "Content-Range",
			In:   "header",
		}
		params.ContentRange = packed[key].(string)
	}
	return params
}

func decodeAPIV1CloudStorageMyUploadUploadIDPutParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1CloudStorageMyUploadUploadIDPutParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: upload_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "upload_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UploadID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "upload_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: Content-Range.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Content-Range",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ContentRange = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Content-Range",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
