// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1AuthRefreshPostOperation                          OperationName = "APIV1AuthRefreshPost"
	APIV1AuthSignInPostOperation                           OperationName = "APIV1AuthSignInPost"
	APIV1AuthSignUpPostOperation                           OperationName = "APIV1AuthSignUpPost"
	APIV1CloudStorageMyDownloadIDGetOperation              OperationName = "APIV1CloudStorageMyDownloadIDGet"
	APIV1CloudStorageMyFileInfoGetOperation                OperationName = "APIV1CloudStorageMyFileInfoGet"
	APIV1CloudStorageMyGetOperation                        OperationName = "APIV1CloudStorageMyGet"
	APIV1CloudStorageMyUploadPostOperation                 OperationName = "APIV1CloudStorageMyUploadPost"
	APIV1CloudStorageMyUploadUploadIDCompletePostOperation OperationName = "APIV1CloudStorageMyUploadUploadIDCompletePost"
	APIV1CloudStorageMyUploadUploadIDGetOperation          OperationName = "APIV1CloudStorageMyUploadUploadIDGet"
	APIV1CloudStorageMyUploadUploadIDPutOperation          OperationName = "APIV1CloudStorageMyUploadUploadIDPut"
)
